language: go
go: 
  - 1.x
script: 
  - go test -coverprofile=cmd.cover.out -coverpkg ./... ./cmd/...
  - go test -coverprofile=parse.cover.out -coverpkg ./... ./parse/...
  - go test -coverprofile=run.cover.out -coverpkg ./... ./run/...
  - echo "mode: set" > coverage.txt && cat *.cover.out | grep -v mode: | sort -r | \
    awk '{if ($1 != last) {print $0; last=$1}}' >> coverage.txt
after_success: bash <(curl -s https://codecov.io/bash)
notifications:
  email: false

