language: go
go: 
  - 1.x
script: 
  - go test -coverprofile=cmd.cover.out ./cmd/...
  - go test -coverprofile=parse.cover.out ./parse/...
  - go test -coverprofile=run.cover.out ./run/...
  - >
    echo "mode: set" > coverage.txt && cat *.cover.out | grep -v mode: | sort -r
    | awk '{if ($1 != last) {print $0; last=$1}}' >> coverage.txt
after_success: bash <(curl -s https://codecov.io/bash)
notifications:
  email:
  on_success: never
  on_failure: never

